### ISSUE TITLE
A JavaScript error occurred in the renderer process

### ISSUE THREAD

**Issue by f0b04707** [tingbot/tide-electron#61]
Got the following weird error "A JavaScript error occurred in the renderer process" which keeps coming again and again, which makes the IDE completely unusable...

![screen shot 2016-11-01 at 13 18 45](https://cloud.githubusercontent.com/assets/1544568/19889579/da3d034a-a035-11e6-878e-204c84195409.png)

Found this, maybe it can help: https://github.com/electron/electron/issues/2479

**Comment by joerick** [comment]
This error's coming from the mDNS library - it's unhappy with a packet that's been received from something on the network. Short of changing to a different zeroconf library, I'm not sure what we can do about this!

**Comment by f0b04707** [comment]
I understand but it makes Tide completely unusable as the error is popping continually... 

Maybe the error could be catch and put in the log file ?

**Comment by joerick** [comment]
Sorry this is so frustrating @WhistleMaster,  this dialog is being shown because of recent changes to exception handling. If you can get to the Javascript console (Window>Toggle Developer Tools), paste the following into a console and hit return.

```
window.onerror = null
```

That'll disable the messages for that document.

**Comment by joerick** [comment]
I don't want to resort to letting errors occur silently again as it gives a bad user experience when things fail - a failed save for example is a unhandled exception at the moment. This should be reported to the user. And buggy libraries that are raising exceptions should be fixed or replaced. 

As far as I know, we can't catch errors from this library using Javascript's try/catch because the error happens in a callback - our code is not involved in the call stack. But if anyone knows of a way that would be a great fix for now.

**Comment by joerick** [comment]
I changed my mind - grab a copy of the latest beta once it's done building :) https://github.com/tingbot/tide-electron/releases/tag/v0.4.6-beta

**Comment by joerick** [comment]
Fixed in 6f8f2c788d615fe093415ace05e259d763bba350
